### ISSUE TITLE
Unable to read "lib\clients.d.ts" from "camo".

### ISSUE THREAD

**Issue by michaeljota** [IndefinitivelyTyped/camo#1]
``` javascript
? What is the dependency name? camo
typings ERR! message Unable to read "lib\clients.d.ts" from "camo". You should check the entry in "typings.json" is correct
typings ERR! caused by https://raw.githubusercontent.com/IndefinitivelyTyped/camo/master/lib/clients.d.ts responded with 404, expected it to equal 200.
```

I look into the tree, and there is a directory named clients, but not a file. 

Thanks again BTW!

**Comment by WorldMaker** [comment]
Interesting. The Node module loader auto-checks a directory for an index.d.ts; looks like typings does not (yet?). (I essentially copied the import here from camo itself...)

**Comment by michaeljota** [comment]
I think maybe the import it's expecting a file, instead of a folder. (?).

**Comment by WorldMaker** [comment]
I filed an issue with typing (typings/typings#173): Node and Typescript in node module resolution mode when given the name of directory try to load an index.\* file in the directory (index.js, index.ts, index.d.ts). Typings doesn't support following that resolution pattern at the moment apparently. I made the simple and easy fix for this. Please try it again.

**Comment by michaeljota** [comment]
Thanks. Seems to work.
